<?php
/**
 * PrestaShift Migration Module
 *
 * @author    marcingajewski.pl <kontakt@marcin.gajewski.pl>
 * @copyright 2026 marcingajewski.pl
 * Modifié par : Thierry Laval <contact@thierrylaval.dev>
 * @copyright 2026 Thierry Laval
 * @license   https://opensource.org/licenses/AFL-3.0 Academic Free License 3.0 (AFL-3.0)
 * @version   1.3.0
 */
namespace PrestaShift\Service\Steps;

use Db;
use PDO;
use PrestaShift\Service\IdMapper;
use PrestaShift\Service\SchemaHelper;

class SpecificPriceMigrationStep
{
    private $db_connection;
    private $prefix;

    /** Columns whose non-zero value narrows who gets the price */
    private static $restrictions = [
        'id_product', 'id_product_attribute', 'id_customer', 'id_group', 'id_country', 'id_currency', 'id_cart',
    ];

    public function __construct($db_connection, $prefix)
    {
        $this->db_connection = $db_connection;
        $this->prefix = $prefix;
    }

    public function process($offset, $limit, $dateFilter = null)
    {
        // specific_price has no date columns — every run reads all rows; the
        // id map turns repeated rows into updates
        $items = $this->getData($offset, $limit);

        if (empty($items)) {
            return ['count' => 0, 'finished' => true];
        }

        IdMapper::prepare('specific_price', array_column($items, 'id_specific_price'));
        IdMapper::prepare('product', array_column($items, 'id_product'));

        $products = [];
        foreach ($items as $item) {
            if ($this->importSpecificPrice($item) && (int)$item['id_product'] > 0) {
                $products[(int)$item['id_product']] = true;
            }
        }

        $this->importPriorities(array_keys($products));

        return ['count' => count($items), 'finished' => false];
    }

    private function getData($offset, $limit)
    {
        $sql = "SELECT * FROM `{$this->prefix}specific_price` ORDER BY `id_specific_price` ASC LIMIT $limit OFFSET $offset";
        $stmt = $this->db_connection->query($sql);
        return $stmt->fetchAll(PDO::FETCH_ASSOC);
    }

    private function importSpecificPrice($data)
    {
        // Prices generated by catalog price rules are rebuilt from the rules
        if (isset($data['id_specific_price_rule']) && (int)$data['id_specific_price_rule'] > 0) {
            return false;
        }

        $row = IdMapper::row('specific_price', $data);

        // A restriction that cannot be translated must drop the price: a price
        // for one customer must not become a price for everybody
        foreach (self::$restrictions as $col) {
            if (isset($data[$col]) && (int)$data[$col] > 0 && (int)$row[$col] <= 0) {
                return false;
            }
        }

        $row['id_shop'] = SchemaHelper::getTargetShopId();
        $row['id_shop_group'] = 0;

        return (bool)SchemaHelper::upsert('specific_price', $row, ['id_specific_price']);
    }

    private function importPriorities(array $sourceProducts)
    {
        if (empty($sourceProducts) || !SchemaHelper::hasTable('specific_price_priority')) {
            return;
        }

        try {
            $rows = $this->db_connection->query("SELECT id_product, priority FROM `{$this->prefix}specific_price_priority`
                WHERE id_product IN (" . implode(',', $sourceProducts) . ") ORDER BY id_shop ASC")->fetchAll(PDO::FETCH_ASSOC);
        } catch (\Exception $e) {
            return;
        }

        $shopId = SchemaHelper::getTargetShopId();
        foreach ($rows as $r) {
            $idProduct = IdMapper::ref('product', (int)$r['id_product']);
            if ($idProduct <= 0) {
                continue;
            }
            Db::getInstance()->execute("DELETE FROM `" . _DB_PREFIX_ . "specific_price_priority` WHERE id_product = $idProduct AND id_shop = $shopId");
            SchemaHelper::insertIgnore('specific_price_priority', [
                'id_shop' => $shopId,
                'id_product' => $idProduct,
                'priority' => $r['priority'],
            ]);
        }
    }
}
