<?php
/**
 * PrestaShift Migration Module
 *
 * @author    marcingajewski.pl <kontakt@marcin.gajewski.pl>
 * @copyright 2026 marcingajewski.pl
 * Modifié par : Thierry Laval <contact@thierrylaval.dev>
 * @copyright 2026 Thierry Laval
 * @license   https://opensource.org/licenses/AFL-3.0 Academic Free License 3.0 (AFL-3.0)
 * @version   1.3.0
 */
namespace PrestaShift\Service;

use Db;

/**
 * Last task of every migration: repairs references of MIGRATED records that
 * point at records missing in the target — the source may already contain
 * such dangling ids, and parts of the data may not have been migrated.
 * PrestaShop 8/9 crashes on some of them when a product is opened (e.g. a
 * product-supplier row with supplier 0 or with a supplier that does not exist).
 *
 * Records that existed in the target before the migration are never touched:
 * every query is restricted to ids created by the migration (id map, not
 * linked).
 */
class IntegrityService
{
    public static function run(array $scope)
    {
        $log = LogService::getInstance();
        $p = _DB_PREFIX_;
        $map = $p . IdMapper::MAP_TABLE;
        $migratedProducts = "JOIN `$map` m ON m.`entity` = 'product' AND m.`linked` = 0 AND m.`target_id` = x.`id_product`";

        $queries = [
            // Supplier associations PrestaShop 8/9 cannot open
            'product_supplier: supplier 0 or missing' => "DELETE x FROM `{$p}product_supplier` x $migratedProducts
                LEFT JOIN `{$p}supplier` s ON s.`id_supplier` = x.`id_supplier`
                WHERE x.`id_supplier` = 0 OR s.`id_supplier` IS NULL",
            'product: missing default supplier' => "UPDATE `{$p}product` x $migratedProducts
                LEFT JOIN `{$p}supplier` s ON s.`id_supplier` = x.`id_supplier`
                SET x.`id_supplier` = 0 WHERE x.`id_supplier` > 0 AND s.`id_supplier` IS NULL",
            'product: missing brand' => "UPDATE `{$p}product` x $migratedProducts
                LEFT JOIN `{$p}manufacturer` b ON b.`id_manufacturer` = x.`id_manufacturer`
                SET x.`id_manufacturer` = 0 WHERE x.`id_manufacturer` > 0 AND b.`id_manufacturer` IS NULL",
            'product: missing default combination' => "UPDATE `{$p}product` x $migratedProducts
                LEFT JOIN `{$p}product_attribute` pa ON pa.`id_product_attribute` = x.`cache_default_attribute`
                SET x.`cache_default_attribute` = 0 WHERE x.`cache_default_attribute` > 0 AND pa.`id_product_attribute` IS NULL",
            'product_shop: missing default combination' => "UPDATE `{$p}product_shop` x $migratedProducts
                LEFT JOIN `{$p}product_attribute` pa ON pa.`id_product_attribute` = x.`cache_default_attribute`
                SET x.`cache_default_attribute` = 0 WHERE x.`cache_default_attribute` > 0 AND pa.`id_product_attribute` IS NULL",
            'category_product: missing category' => "DELETE x FROM `{$p}category_product` x $migratedProducts
                LEFT JOIN `{$p}category` c ON c.`id_category` = x.`id_category`
                WHERE c.`id_category` IS NULL",
            'product: missing default category' => "UPDATE `{$p}product` x $migratedProducts
                LEFT JOIN `{$p}category` c ON c.`id_category` = x.`id_category_default`
                SET x.`id_category_default` = " . (int) \Configuration::get('PS_HOME_CATEGORY') . " WHERE c.`id_category` IS NULL",
            'product_shop: missing default category' => "UPDATE `{$p}product_shop` x $migratedProducts
                LEFT JOIN `{$p}category` c ON c.`id_category` = x.`id_category_default`
                SET x.`id_category_default` = " . (int) \Configuration::get('PS_HOME_CATEGORY') . " WHERE c.`id_category` IS NULL",
        ];

        foreach ($queries as $label => $sql) {
            try {
                if (Db::getInstance()->execute($sql)) {
                    $affected = (int) Db::getInstance()->Affected_Rows();
                    if ($affected > 0) {
                        $log->info("Integrity: $label — fixed $affected row(s)");
                    }
                }
            } catch (\Throwable $e) {
                $log->warning("Integrity: $label — " . $e->getMessage());
            }
        }

        // Specific prices generated by catalog price rules
        if (empty($scope) || !empty($scope['specific_prices'])) {
            try {
                \SpecificPriceRule::applyAllRules();
            } catch (\Throwable $e) {
                $log->warning('Integrity: applying catalog price rules failed — ' . $e->getMessage());
            }
        }

        // Default carrier must be an active one
        if (empty($scope) || !empty($scope['carriers'])) {
            $default = (int) \Configuration::get('PS_CARRIER_DEFAULT');
            $ok = $default > 0 && (int) Db::getInstance()->getValue("SELECT 1 FROM `{$p}carrier` WHERE id_carrier = $default AND active = 1 AND deleted = 0", false);
            if (!$ok) {
                $first = (int) Db::getInstance()->getValue("SELECT id_carrier FROM `{$p}carrier` WHERE active = 1 AND deleted = 0 ORDER BY position ASC, id_carrier ASC", false);
                if ($first > 0) {
                    \Configuration::updateValue('PS_CARRIER_DEFAULT', $first);
                }
            }
        }
    }
}
